// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMsg3.proto

package com.xuren.gameserver.proto;

public final class ProtoMsg3 {
  private ProtoMsg3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.xuren.gameserver.proto.HeadType}
   */
  public enum HeadType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG_LOGIN_CS = 0;</code>
     */
    MSG_LOGIN_CS(0),
    /**
     * <code>MSG_LOGIN_SC = 1;</code>
     */
    MSG_LOGIN_SC(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MSG_LOGIN_CS = 0;</code>
     */
    public static final int MSG_LOGIN_CS_VALUE = 0;
    /**
     * <code>MSG_LOGIN_SC = 1;</code>
     */
    public static final int MSG_LOGIN_SC_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HeadType valueOf(int value) {
      return forNumber(value);
    }

    public static HeadType forNumber(int value) {
      switch (value) {
        case 0: return MSG_LOGIN_CS;
        case 1: return MSG_LOGIN_SC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HeadType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HeadType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HeadType>() {
            public HeadType findValueByNumber(int number) {
              return HeadType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xuren.gameserver.proto.ProtoMsg3.getDescriptor().getEnumTypes().get(0);
    }

    private static final HeadType[] VALUES = values();

    public static HeadType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HeadType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.xuren.gameserver.proto.HeadType)
  }

  public interface MsgLoginCSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xuren.gameserver.proto.MsgLoginCS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    com.xuren.gameserver.proto.ProtoMsg3.HeadType getType();

    /**
     * <code>string user_name = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string user_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.xuren.gameserver.proto.MsgLoginCS}
   */
  public  static final class MsgLoginCS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xuren.gameserver.proto.MsgLoginCS)
      MsgLoginCSOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgLoginCS.newBuilder() to construct.
    private MsgLoginCS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgLoginCS() {
      type_ = 0;
      userName_ = "";
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgLoginCS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginCS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginCS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.class, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    public com.xuren.gameserver.proto.ProtoMsg3.HeadType getType() {
      com.xuren.gameserver.proto.ProtoMsg3.HeadType result = com.xuren.gameserver.proto.ProtoMsg3.HeadType.valueOf(type_);
      return result == null ? com.xuren.gameserver.proto.ProtoMsg3.HeadType.UNRECOGNIZED : result;
    }

    public static final int USER_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>string user_name = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string user_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.xuren.gameserver.proto.ProtoMsg3.HeadType.MSG_LOGIN_CS.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.xuren.gameserver.proto.ProtoMsg3.HeadType.MSG_LOGIN_CS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS)) {
        return super.equals(obj);
      }
      com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS other = (com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xuren.gameserver.proto.MsgLoginCS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xuren.gameserver.proto.MsgLoginCS)
        com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginCS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginCS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.class, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.Builder.class);
      }

      // Construct using com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        userName_ = "";

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginCS_descriptor;
      }

      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS getDefaultInstanceForType() {
        return com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.getDefaultInstance();
      }

      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS build() {
        com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS buildPartial() {
        com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS result = new com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS(this);
        result.type_ = type_;
        result.userName_ = userName_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS) {
          return mergeFrom((com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS other) {
        if (other == com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public com.xuren.gameserver.proto.ProtoMsg3.HeadType getType() {
        com.xuren.gameserver.proto.ProtoMsg3.HeadType result = com.xuren.gameserver.proto.ProtoMsg3.HeadType.valueOf(type_);
        return result == null ? com.xuren.gameserver.proto.ProtoMsg3.HeadType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public Builder setType(com.xuren.gameserver.proto.ProtoMsg3.HeadType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string user_name = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_name = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 2;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xuren.gameserver.proto.MsgLoginCS)
    }

    // @@protoc_insertion_point(class_scope:com.xuren.gameserver.proto.MsgLoginCS)
    private static final com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS();
    }

    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgLoginCS>
        PARSER = new com.google.protobuf.AbstractParser<MsgLoginCS>() {
      public MsgLoginCS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgLoginCS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgLoginCS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgLoginCS> getParserForType() {
      return PARSER;
    }

    public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgLoginSCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xuren.gameserver.proto.MsgLoginSC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    com.xuren.gameserver.proto.ProtoMsg3.HeadType getType();

    /**
     * <code>int32 code = 2;</code>
     */
    int getCode();

    /**
     * <code>string session_id = 3;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>string session_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();
  }
  /**
   * Protobuf type {@code com.xuren.gameserver.proto.MsgLoginSC}
   */
  public  static final class MsgLoginSC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xuren.gameserver.proto.MsgLoginSC)
      MsgLoginSCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgLoginSC.newBuilder() to construct.
    private MsgLoginSC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgLoginSC() {
      type_ = 0;
      code_ = 0;
      sessionId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgLoginSC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              code_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginSC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginSC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.class, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    public com.xuren.gameserver.proto.ProtoMsg3.HeadType getType() {
      com.xuren.gameserver.proto.ProtoMsg3.HeadType result = com.xuren.gameserver.proto.ProtoMsg3.HeadType.valueOf(type_);
      return result == null ? com.xuren.gameserver.proto.ProtoMsg3.HeadType.UNRECOGNIZED : result;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object sessionId_;
    /**
     * <code>string session_id = 3;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string session_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.xuren.gameserver.proto.ProtoMsg3.HeadType.MSG_LOGIN_CS.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sessionId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.xuren.gameserver.proto.ProtoMsg3.HeadType.MSG_LOGIN_CS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sessionId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC)) {
        return super.equals(obj);
      }
      com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC other = (com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (getCode()
          == other.getCode());
      result = result && getSessionId()
          .equals(other.getSessionId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xuren.gameserver.proto.MsgLoginSC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xuren.gameserver.proto.MsgLoginSC)
        com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginSC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginSC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.class, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.Builder.class);
      }

      // Construct using com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        code_ = 0;

        sessionId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_MsgLoginSC_descriptor;
      }

      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC getDefaultInstanceForType() {
        return com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.getDefaultInstance();
      }

      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC build() {
        com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC buildPartial() {
        com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC result = new com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC(this);
        result.type_ = type_;
        result.code_ = code_;
        result.sessionId_ = sessionId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC) {
          return mergeFrom((com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC other) {
        if (other == com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public com.xuren.gameserver.proto.ProtoMsg3.HeadType getType() {
        com.xuren.gameserver.proto.ProtoMsg3.HeadType result = com.xuren.gameserver.proto.ProtoMsg3.HeadType.valueOf(type_);
        return result == null ? com.xuren.gameserver.proto.ProtoMsg3.HeadType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public Builder setType(com.xuren.gameserver.proto.ProtoMsg3.HeadType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 2;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <code>string session_id = 3;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string session_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string session_id = 3;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string session_id = 3;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>string session_id = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xuren.gameserver.proto.MsgLoginSC)
    }

    // @@protoc_insertion_point(class_scope:com.xuren.gameserver.proto.MsgLoginSC)
    private static final com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC();
    }

    public static com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgLoginSC>
        PARSER = new com.google.protobuf.AbstractParser<MsgLoginSC>() {
      public MsgLoginSC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgLoginSC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgLoginSC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgLoginSC> getParserForType() {
      return PARSER;
    }

    public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xuren.gameserver.proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    com.xuren.gameserver.proto.ProtoMsg3.HeadType getType();

    /**
     * <code>string session_id = 2;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>string session_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
     */
    boolean hasMsgLoginCS();
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
     */
    com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS getMsgLoginCS();
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
     */
    com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCSOrBuilder getMsgLoginCSOrBuilder();

    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
     */
    boolean hasMsgLoginSC();
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
     */
    com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC getMsgLoginSC();
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
     */
    com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSCOrBuilder getMsgLoginSCOrBuilder();
  }
  /**
   * Protobuf type {@code com.xuren.gameserver.proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xuren.gameserver.proto.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      sessionId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 26: {
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.Builder subBuilder = null;
              if (msgLoginCS_ != null) {
                subBuilder = msgLoginCS_.toBuilder();
              }
              msgLoginCS_ = input.readMessage(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msgLoginCS_);
                msgLoginCS_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.Builder subBuilder = null;
              if (msgLoginSC_ != null) {
                subBuilder = msgLoginSC_.toBuilder();
              }
              msgLoginSC_ = input.readMessage(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msgLoginSC_);
                msgLoginSC_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xuren.gameserver.proto.ProtoMsg3.Message.class, com.xuren.gameserver.proto.ProtoMsg3.Message.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
     */
    public com.xuren.gameserver.proto.ProtoMsg3.HeadType getType() {
      com.xuren.gameserver.proto.ProtoMsg3.HeadType result = com.xuren.gameserver.proto.ProtoMsg3.HeadType.valueOf(type_);
      return result == null ? com.xuren.gameserver.proto.ProtoMsg3.HeadType.UNRECOGNIZED : result;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object sessionId_;
    /**
     * <code>string session_id = 2;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string session_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGLOGINCS_FIELD_NUMBER = 3;
    private com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS msgLoginCS_;
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
     */
    public boolean hasMsgLoginCS() {
      return msgLoginCS_ != null;
    }
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
     */
    public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS getMsgLoginCS() {
      return msgLoginCS_ == null ? com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.getDefaultInstance() : msgLoginCS_;
    }
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
     */
    public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCSOrBuilder getMsgLoginCSOrBuilder() {
      return getMsgLoginCS();
    }

    public static final int MSGLOGINSC_FIELD_NUMBER = 4;
    private com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC msgLoginSC_;
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
     */
    public boolean hasMsgLoginSC() {
      return msgLoginSC_ != null;
    }
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
     */
    public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC getMsgLoginSC() {
      return msgLoginSC_ == null ? com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.getDefaultInstance() : msgLoginSC_;
    }
    /**
     * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
     */
    public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSCOrBuilder getMsgLoginSCOrBuilder() {
      return getMsgLoginSC();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.xuren.gameserver.proto.ProtoMsg3.HeadType.MSG_LOGIN_CS.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionId_);
      }
      if (msgLoginCS_ != null) {
        output.writeMessage(3, getMsgLoginCS());
      }
      if (msgLoginSC_ != null) {
        output.writeMessage(4, getMsgLoginSC());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.xuren.gameserver.proto.ProtoMsg3.HeadType.MSG_LOGIN_CS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionId_);
      }
      if (msgLoginCS_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMsgLoginCS());
      }
      if (msgLoginSC_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMsgLoginSC());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xuren.gameserver.proto.ProtoMsg3.Message)) {
        return super.equals(obj);
      }
      com.xuren.gameserver.proto.ProtoMsg3.Message other = (com.xuren.gameserver.proto.ProtoMsg3.Message) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getSessionId()
          .equals(other.getSessionId());
      result = result && (hasMsgLoginCS() == other.hasMsgLoginCS());
      if (hasMsgLoginCS()) {
        result = result && getMsgLoginCS()
            .equals(other.getMsgLoginCS());
      }
      result = result && (hasMsgLoginSC() == other.hasMsgLoginSC());
      if (hasMsgLoginSC()) {
        result = result && getMsgLoginSC()
            .equals(other.getMsgLoginSC());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      if (hasMsgLoginCS()) {
        hash = (37 * hash) + MSGLOGINCS_FIELD_NUMBER;
        hash = (53 * hash) + getMsgLoginCS().hashCode();
      }
      if (hasMsgLoginSC()) {
        hash = (37 * hash) + MSGLOGINSC_FIELD_NUMBER;
        hash = (53 * hash) + getMsgLoginSC().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuren.gameserver.proto.ProtoMsg3.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xuren.gameserver.proto.ProtoMsg3.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xuren.gameserver.proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xuren.gameserver.proto.Message)
        com.xuren.gameserver.proto.ProtoMsg3.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xuren.gameserver.proto.ProtoMsg3.Message.class, com.xuren.gameserver.proto.ProtoMsg3.Message.Builder.class);
      }

      // Construct using com.xuren.gameserver.proto.ProtoMsg3.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        sessionId_ = "";

        if (msgLoginCSBuilder_ == null) {
          msgLoginCS_ = null;
        } else {
          msgLoginCS_ = null;
          msgLoginCSBuilder_ = null;
        }
        if (msgLoginSCBuilder_ == null) {
          msgLoginSC_ = null;
        } else {
          msgLoginSC_ = null;
          msgLoginSCBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xuren.gameserver.proto.ProtoMsg3.internal_static_com_xuren_gameserver_proto_Message_descriptor;
      }

      public com.xuren.gameserver.proto.ProtoMsg3.Message getDefaultInstanceForType() {
        return com.xuren.gameserver.proto.ProtoMsg3.Message.getDefaultInstance();
      }

      public com.xuren.gameserver.proto.ProtoMsg3.Message build() {
        com.xuren.gameserver.proto.ProtoMsg3.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xuren.gameserver.proto.ProtoMsg3.Message buildPartial() {
        com.xuren.gameserver.proto.ProtoMsg3.Message result = new com.xuren.gameserver.proto.ProtoMsg3.Message(this);
        result.type_ = type_;
        result.sessionId_ = sessionId_;
        if (msgLoginCSBuilder_ == null) {
          result.msgLoginCS_ = msgLoginCS_;
        } else {
          result.msgLoginCS_ = msgLoginCSBuilder_.build();
        }
        if (msgLoginSCBuilder_ == null) {
          result.msgLoginSC_ = msgLoginSC_;
        } else {
          result.msgLoginSC_ = msgLoginSCBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuren.gameserver.proto.ProtoMsg3.Message) {
          return mergeFrom((com.xuren.gameserver.proto.ProtoMsg3.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xuren.gameserver.proto.ProtoMsg3.Message other) {
        if (other == com.xuren.gameserver.proto.ProtoMsg3.Message.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasMsgLoginCS()) {
          mergeMsgLoginCS(other.getMsgLoginCS());
        }
        if (other.hasMsgLoginSC()) {
          mergeMsgLoginSC(other.getMsgLoginSC());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xuren.gameserver.proto.ProtoMsg3.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xuren.gameserver.proto.ProtoMsg3.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public com.xuren.gameserver.proto.ProtoMsg3.HeadType getType() {
        com.xuren.gameserver.proto.ProtoMsg3.HeadType result = com.xuren.gameserver.proto.ProtoMsg3.HeadType.valueOf(type_);
        return result == null ? com.xuren.gameserver.proto.ProtoMsg3.HeadType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public Builder setType(com.xuren.gameserver.proto.ProtoMsg3.HeadType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.HeadType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <code>string session_id = 2;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string session_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string session_id = 2;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string session_id = 2;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>string session_id = 2;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS msgLoginCS_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.Builder, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCSOrBuilder> msgLoginCSBuilder_;
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
       */
      public boolean hasMsgLoginCS() {
        return msgLoginCSBuilder_ != null || msgLoginCS_ != null;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
       */
      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS getMsgLoginCS() {
        if (msgLoginCSBuilder_ == null) {
          return msgLoginCS_ == null ? com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.getDefaultInstance() : msgLoginCS_;
        } else {
          return msgLoginCSBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
       */
      public Builder setMsgLoginCS(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS value) {
        if (msgLoginCSBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgLoginCS_ = value;
          onChanged();
        } else {
          msgLoginCSBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
       */
      public Builder setMsgLoginCS(
          com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.Builder builderForValue) {
        if (msgLoginCSBuilder_ == null) {
          msgLoginCS_ = builderForValue.build();
          onChanged();
        } else {
          msgLoginCSBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
       */
      public Builder mergeMsgLoginCS(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS value) {
        if (msgLoginCSBuilder_ == null) {
          if (msgLoginCS_ != null) {
            msgLoginCS_ =
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.newBuilder(msgLoginCS_).mergeFrom(value).buildPartial();
          } else {
            msgLoginCS_ = value;
          }
          onChanged();
        } else {
          msgLoginCSBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
       */
      public Builder clearMsgLoginCS() {
        if (msgLoginCSBuilder_ == null) {
          msgLoginCS_ = null;
          onChanged();
        } else {
          msgLoginCS_ = null;
          msgLoginCSBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
       */
      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.Builder getMsgLoginCSBuilder() {
        
        onChanged();
        return getMsgLoginCSFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
       */
      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCSOrBuilder getMsgLoginCSOrBuilder() {
        if (msgLoginCSBuilder_ != null) {
          return msgLoginCSBuilder_.getMessageOrBuilder();
        } else {
          return msgLoginCS_ == null ?
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.getDefaultInstance() : msgLoginCS_;
        }
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginCS msgLoginCS = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.Builder, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCSOrBuilder> 
          getMsgLoginCSFieldBuilder() {
        if (msgLoginCSBuilder_ == null) {
          msgLoginCSBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCS.Builder, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginCSOrBuilder>(
                  getMsgLoginCS(),
                  getParentForChildren(),
                  isClean());
          msgLoginCS_ = null;
        }
        return msgLoginCSBuilder_;
      }

      private com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC msgLoginSC_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.Builder, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSCOrBuilder> msgLoginSCBuilder_;
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
       */
      public boolean hasMsgLoginSC() {
        return msgLoginSCBuilder_ != null || msgLoginSC_ != null;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
       */
      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC getMsgLoginSC() {
        if (msgLoginSCBuilder_ == null) {
          return msgLoginSC_ == null ? com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.getDefaultInstance() : msgLoginSC_;
        } else {
          return msgLoginSCBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
       */
      public Builder setMsgLoginSC(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC value) {
        if (msgLoginSCBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgLoginSC_ = value;
          onChanged();
        } else {
          msgLoginSCBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
       */
      public Builder setMsgLoginSC(
          com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.Builder builderForValue) {
        if (msgLoginSCBuilder_ == null) {
          msgLoginSC_ = builderForValue.build();
          onChanged();
        } else {
          msgLoginSCBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
       */
      public Builder mergeMsgLoginSC(com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC value) {
        if (msgLoginSCBuilder_ == null) {
          if (msgLoginSC_ != null) {
            msgLoginSC_ =
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.newBuilder(msgLoginSC_).mergeFrom(value).buildPartial();
          } else {
            msgLoginSC_ = value;
          }
          onChanged();
        } else {
          msgLoginSCBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
       */
      public Builder clearMsgLoginSC() {
        if (msgLoginSCBuilder_ == null) {
          msgLoginSC_ = null;
          onChanged();
        } else {
          msgLoginSC_ = null;
          msgLoginSCBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
       */
      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.Builder getMsgLoginSCBuilder() {
        
        onChanged();
        return getMsgLoginSCFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
       */
      public com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSCOrBuilder getMsgLoginSCOrBuilder() {
        if (msgLoginSCBuilder_ != null) {
          return msgLoginSCBuilder_.getMessageOrBuilder();
        } else {
          return msgLoginSC_ == null ?
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.getDefaultInstance() : msgLoginSC_;
        }
      }
      /**
       * <code>.com.xuren.gameserver.proto.MsgLoginSC msgLoginSC = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.Builder, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSCOrBuilder> 
          getMsgLoginSCFieldBuilder() {
        if (msgLoginSCBuilder_ == null) {
          msgLoginSCBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSC.Builder, com.xuren.gameserver.proto.ProtoMsg3.MsgLoginSCOrBuilder>(
                  getMsgLoginSC(),
                  getParentForChildren(),
                  isClean());
          msgLoginSC_ = null;
        }
        return msgLoginSCBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xuren.gameserver.proto.Message)
    }

    // @@protoc_insertion_point(class_scope:com.xuren.gameserver.proto.Message)
    private static final com.xuren.gameserver.proto.ProtoMsg3.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xuren.gameserver.proto.ProtoMsg3.Message();
    }

    public static com.xuren.gameserver.proto.ProtoMsg3.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.xuren.gameserver.proto.ProtoMsg3.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xuren_gameserver_proto_MsgLoginCS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xuren_gameserver_proto_MsgLoginCS_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xuren_gameserver_proto_MsgLoginSC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xuren_gameserver_proto_MsgLoginSC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xuren_gameserver_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xuren_gameserver_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ProtoMsg3.proto\022\032com.xuren.gameserver." +
      "proto\"e\n\nMsgLoginCS\0222\n\004type\030\001 \001(\0162$.com." +
      "xuren.gameserver.proto.HeadType\022\021\n\tuser_" +
      "name\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\"b\n\nMsgLogin" +
      "SC\0222\n\004type\030\001 \001(\0162$.com.xuren.gameserver." +
      "proto.HeadType\022\014\n\004code\030\002 \001(\005\022\022\n\nsession_" +
      "id\030\003 \001(\t\"\311\001\n\007Message\0222\n\004type\030\001 \001(\0162$.com" +
      ".xuren.gameserver.proto.HeadType\022\022\n\nsess" +
      "ion_id\030\002 \001(\t\022:\n\nmsgLoginCS\030\003 \001(\0132&.com.x" +
      "uren.gameserver.proto.MsgLoginCS\022:\n\nmsgL" +
      "oginSC\030\004 \001(\0132&.com.xuren.gameserver.prot" +
      "o.MsgLoginSC*.\n\010HeadType\022\020\n\014MSG_LOGIN_CS" +
      "\020\000\022\020\n\014MSG_LOGIN_SC\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xuren_gameserver_proto_MsgLoginCS_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xuren_gameserver_proto_MsgLoginCS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xuren_gameserver_proto_MsgLoginCS_descriptor,
        new java.lang.String[] { "Type", "UserName", "Password", });
    internal_static_com_xuren_gameserver_proto_MsgLoginSC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xuren_gameserver_proto_MsgLoginSC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xuren_gameserver_proto_MsgLoginSC_descriptor,
        new java.lang.String[] { "Type", "Code", "SessionId", });
    internal_static_com_xuren_gameserver_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_xuren_gameserver_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xuren_gameserver_proto_Message_descriptor,
        new java.lang.String[] { "Type", "SessionId", "MsgLoginCS", "MsgLoginSC", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
